set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports bor]
set_property PACKAGE_PIN K4 [get_ports a]
set_property PACKAGE_PIN N8 [get_ports b]
set_property PACKAGE_PIN N4 [get_ports c]
set_property PACKAGE_PIN L4 [get_ports d]
set_property PACKAGE_PIN M4 [get_ports bor]

