
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]
set_property PACKAGE_PIN K4 [get_ports CLK]
set_property PACKAGE_PIN Y1 [get_ports J]
set_property PACKAGE_PIN W3 [get_ports K]
set_property PACKAGE_PIN L4 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports J]
set_property IOSTANDARD LVCMOS33 [get_ports K]
set_property IOSTANDARD LVCMOS33 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports Qn]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]

set_property PACKAGE_PIN M4 [get_ports Qn]
set_property PACKAGE_PIN U2 [get_ports RESET]
